version: '3.8'

services:
  db:
    image: mysql:8.3 # for testing through MySQLContainer
    container_name: lunch_db
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: lunch_app
        MYSQL_USER: lunchuser
        MYSQL_PASSWORD: lunchpassword
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - lunch_db_data:/var/lib/mysql

volumes:
  lunch_db_data: